account/urls.py
from django.urls import path
from . import views

urlpatterns= [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup")
]

commapp/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.main, name="main"),
    path('about/', views.about, name="about"),
    path('board/', views.board, name="board"),
    path('board/new/', views.board_post, name="board_post"),
    path('board/<int:pk>/', views.board_detail, name="board_detail"),
    path('board_update/<int:pk>/', views.board_update, name="board_update"),
    path('board_delete/<int:pk>', views.board_delete, name="board_delete"),
    path('comment_create/<int:pk>/', views.comment_create, name="comment_create"),
    path('comment_update/<int:pk>/', views.comment_update, name="comment_update"),
    path('comment_delete/<int:pk>', views.comment_delete, name="comment_delete"),
    path('recomment_create/<int:c_pk>/', views.recomment_create, name="recomment_create"),
    path('recomment_delete/<int:rc_pk>/', views.recomment_delete, name="recomment_delete"),
    path('board/search/', views.search,
    name="search"),
    path('user/<str:username>/',views.GithubUserView.as_view(), name="user"),
    path('commit_rank/',views.commit_rank, name="commit_rank"),
    path('mypage/',views.mypage, name="mypage"),
    path('commit/',views.Co, name="Co"),
    ] 

commprj/urls.py
from django.urls import include,path
from django.contrib import admin
from commapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.main, name="main"),
    path('', include('commapp.urls')),
    path('test/', views.test, name="test"),
    path('account/',include('account.urls')),
    path('markdownx/', include('markdownx.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

commapp/models.py
import os
from django.db import models
from commprj import settings
from account.models import CustomUser
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
# from django.contrib.auth.models import User

# Create your models here.
# User = settings.AUTH_USER_MODEL
class comm(models.Model):
    title = models.CharField('',max_length=50)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    # title = models.CharField('',max_length=50)
    # author = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    text = MarkdownxField()
    img = models.ImageField(blank=True, null=True, upload_to='lion_photo/%y/%m/%d/')
    file = models.FileField(blank=True, null=True,upload_to='lion_file/%y/%m/%d/')
    OPTION = (
        ('talk','TALK'),
        ('issue','ISSUE'),
        ('project','PROJECT'),
        ('connect','CONNECT'),
    )
    tag = models.CharField('카테고리',max_length=7, choices=OPTION)

    def __str__(self):
        return self.title

    def get_content_markdown(self):
        return markdown(self.content)

    def get_file_name(self):
        return os.path.basename(self.file.name)

class Comment(models.Model):
    post = models.ForeignKey(comm, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user}::{self.content}'

class ReComment(models.Model):
    post = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    content = models.CharField("🐾",max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post


class Commit(models.Model):
    user = models.ForeignKey(CustomUser, related_name = "userof", on_delete=models.CASCADE)
    gitName = models.CharField(max_length=50)
    commit = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.gitName}'

commapp/forms.py
from dataclasses import field 
from django import forms
from .models import comm, Comment, ReComment

class commForm(forms.ModelForm):
    class Meta:
        model = comm
        fields = ('title','tag','text', 'img', 'file')
        widgets = {
            'title': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 90%',
                'placeholder': '제목을 입력하세요'
                }),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )
        widgets = {
            'content': forms.Textarea(attrs={
                'class': "commentform",
                'placeholder': '댓글을 작성하세요'
                }),
        }


class ReCommentForm(forms.ModelForm):
    class Meta:
        model = ReComment
        fields = ('content', )

# class RegisterForm(UserCreationForm):
#     email = forms.EmailField(label="likelion 이메일")
#     github_email = forms.EmailField(label="github 아이디")
#     class Meta:
#         model = User
#         fields = ['username','password1','password2','github_email', 'email']

# class loginForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['email','password1']

commapp/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import get_object_or_404, redirect, render
from django.core.exceptions import PermissionDenied
from .models import comm, Comment,  ReComment, Commit
from django.views.generic import View, CreateView
from commapp.forms import CommentForm, commForm, ReCommentForm
import requests
from account.models import CustomUser
import base64
from urllib import parse
import re
# Create your views here.

def main(request):
    return render(request, 'main.html')

def test(request):
    return render(request, 'test.html')

def about(request):
    return render(request, 'about.html')

def board_post(request):
    if request.method == 'POST' or request.method=='FILES': #POST요청 폼의 버튼을 눌렀다
        form  = commForm(request.POST, request.FILES) #form 유효성 확인
        if form.is_valid():
            c = form.save(commit=False) #db에 당장 저장x
            c.user = request.user
            c.save()
            return redirect('board_detail', pk = c.pk)
    else: #GET요청 웹 브라우저에서 페이지 접속
        form = commForm()
    return render(request, 'board_post.html', {'form':form})

def board(request):
    c = comm.objects.all().order_by('-id')
    return render(request, 'board.html',{'comm':c})

def board_detail(request, pk):
    # all = comm.objects.all()
    c = get_object_or_404(comm, pk=pk)
    form = CommentForm()
    reform = ReCommentForm()
    return render(request, 'board_detail.html',{'comm':c, 'comment_form':form,'recomment_form':reform})

def board_update(request, pk):
    c = get_object_or_404(comm,pk=pk)
    if(request.method == "POST" or request.method == 'FILES'):
        form = commForm(request.POST, request.FILES, instance=c)
        if(form.is_valid()):
            c = form.save(commit=False)
            c.save()
        return redirect('board_detail', pk=c.pk)
    else:
        form = commForm(instance=c)
        return render(request, 'board_post.html', {'form':form})

def board_delete(request,pk):
    c = get_object_or_404(comm,pk=pk)
    c.delete()
    return redirect('board')

def comment_create(request, pk):
    filled_form = CommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.post = get_object_or_404(comm, pk=pk)
        finished_form.user = request.user
        finished_form.save()
    return redirect('board_detail', pk)

def comment_update(request, pk):
    c = get_object_or_404(Comment,pk=pk) # 모델로부터 객체를 받을 때 객체가 있으면 받고, 없을 시 404 에러 페이지를 보여줌
    p = get_object_or_404(comm,pk=c.post.pk)
    if(request.method == "POST"):
        form = CommentForm(request.POST, instance=c)
        if(form.is_valid()):
            c = form.save(commit=False)
            c.save()
        return redirect('board_detail', pk=p.pk) #댓글 모델의 포스트pk값을 받아서 디테일페이지/pk로 사요
    else:
        form = CommentForm(instance=c) #CommentForm에 정보 넣음
        return render(request, 'board_post.html', {'form':form}) #render함수를 통해 board_post에 form을 넣는다.
def comment_delete(request, pk):
    c = get_object_or_404(Comment,pk=pk)
    p = get_object_or_404(comm, pk=c.post.pk)
    c.delete()
    return redirect('board_detail', pk=p.pk)

def recomment_create(request,c_pk):
    filled_form = ReCommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.post = get_object_or_404(Comment, pk=c_pk)
        finished_form.user = request.user
        finished_form.save()
    return redirect('board_detail', pk=finished_form.post.post.pk)

def recomment_delete(request, rc_pk):
    # c = get_object_or_404(Comment, pk=pk)
    rc = get_object_or_404(ReComment, pk=rc_pk)
    p = get_object_or_404(comm, pk=rc.post.post.pk)
    rc.delete()
    return redirect('board_detail', pk=p.pk)

def search(request):
    post=comm.objects.all().order_by('-id')

    q = request.POST.get('search','')
    if q:
        post=post.filter(title__icontains=q)
        return render(request, 'search.html',{'post':post, 'q':q})
    else:
        return render(request, 'search.html',{'post':post})

class GithubUserView(View):
    def get(self, request, username):
        # username,repos = requset.GET['username','repos']
        # repos = requset.GET['repos']
        url1 = 'https://api.github.com/users/%s/repos?per_page=100' %(username)
        response1 = requests.get(url1).json()
        arr = []
        count=0
        for i in range(len(response1)-1, 0,-1):
            push=response1[i]["pushed_at"]
            push1 = push[0:10]
            push2 = push1.split('-')
            push3 = ''.join(push2)
            if(20220803 <= int(push3)):
                arr.append(response1[i]["name"])
       
        for i in arr:
            url = 'https://api.github.com/repos/%s/%s/commits?per_page=100' %(username, i)
            response = requests.get(url).json()
            for j in range(len(response)):
                time=response[j]["commit"]["author"]["date"]
                string1 = time[0:10]
                string1 = string1.split('-')
                string = ''.join(string1)
                if int(string) >= 20220803 :
                    count += 1
                else:
                    break
        commit=Commit.objects.all()
        if commit.filter(gitName__icontains=username).exists():
            # commit.author['username'].update(
            #     commit = count
            # )
            commit.filter(gitName=username).update(commit = count)
        else:
            commit.gitName = username
            commit.commit = count
        return render(request, 'commit.html',{'name':arr, 'repos':count})
        # return render(requset, 'commit.html',{'name':username, 'repos':arr})

def commit_rank(request):
    commit = Commit.objects.all().order_by('-commit')
    return render(request, 'commit_rank.html',{'commit':commit})

def mypage(request):
    # n=request.user
    # m=str(request.user)
    n=CustomUser.objects.get(username=request.user.username)
    name1=n.git
    # name1 = n.git
    # x = "namseohyeon"
    # repo = "DAASHeo
    # x = "namseohyeon"
    # name = "DAASHeo"
    # repo = "DAASHeo"
    commit=Commit.objects.all()
    # # # commit.gitName=request.POST['gitName']
    url = 'https://api.github.com/repos/%s/%s/readme' %(name1,name1)
    response = requests.get(url).json()
    readme=response.get('content')
    if readme:
    # # read=readme.decode("UTF-8")
        r=base64.b64decode(readme)
        read=r.decode("UTF-8")
        x=read.replace('<div align="center">','').replace('</div>','').replace('<h1>','#').replace('<h2>','##').replace('<h3>','###').replace('<h4>','####').replace('<h5>','#####').replace('<h6>','######').replace('<p>','').replace('</h1>','').replace('</h2>','').replace('</h3>','').replace('</h4>','').replace('</h5>','').replace('</h6>','').replace('</p>','').replace('<br>','').replace('<br/>','').replace('<strong>','**').replace('</strong>','**').replace('<img src="','![image](').replace('/>',')').replace('<a href="','[''](').replace('">',')').replace('</a>','')
    else:
        x = "git readme가 없습니다"
    p_url = 'https://api.github.com/users/%s' %(name1)
    p_response = requests.get(p_url).json()
    #.replace('<a href="','(').replace('">',')')
    #.replace('<img src="','![image](').replace('/>',')').replace('<img src="','![image](')
    #.replace('<a href="','[](').replace('>',')')
    #.replace('>',')').replace('<a href="','[](')
    # .replace('">',')').replace('<img src="','![image](').replace('/>',')')
    # q=[m.start() for m in re.finditer('<', x)]
    # for i in range(len(q)):
    # while True:
    # #     if x.find("<") != -1:
    # i3=x3.find("<a>")
    # x4=x3[:i3]
    # i4=x3.find("</a>")
    # x5=x[i4:]
    # x6=x4+x5
        # else:
        #     break
    #readme=parse.urlencode(response, encoding='UTF-8', doseq=True)
                # .then((response) => response.json())
                # .then((data) =>{
                #     console.log(data) // json 파일
                #     console.log(data.content) //파일 내용 base64로 받아와진다
                #     document.write(decodeURIComponent(atob(data.content))); //utf-8로 디코딩
                # });
    return render(request, 'mypage.html',{'commit':commit,'readme':x,'img':p_response['avatar_url']})
    #return render(request, 'mypage.html',{'commit':commit,'readme':x})



def Co(request):
    # username,repos = requset.GET['username','repos']
    # repos = requset.GET['repos']
    username=request.POST['gitName']  
    # CustomUser.git =request.POST['gitName'] 
    url1 = 'https://api.github.com/users/%s/repos?per_page=100' %(username)
    response1 = requests.get(url1).json()
    arr = []
    count=0
    for i in range(len(response1)-1, 0,-1):
        push=response1[i]["pushed_at"]
        push1 = push[0:10]
        push2 = push1.split('-')
        push3 = ''.join(push2)
        if(20220815 <= int(push3)):
            arr.append(response1[i]["name"])
    
    for i in arr:
        url = 'https://api.github.com/repos/%s/%s/commits?per_page=100' %(username, i)
        response = requests.get(url).json()
        for j in range(len(response)):
            time=response[j]["commit"]["author"]["date"]
            string1 = time[0:10]
            string1 = string1.split('-')
            string = ''.join(string1)
            if int(string) >= 20220815 :
                count += 1
            else:
                break
    commit=Commit.objects.all()
    if commit.filter(gitName__icontains=username).exists():
        commit.filter(gitName=username).update(commit = count)
    else:
        Commit.objects.create(
            user = request.user,
            gitName = username,
            commit = count
        )
    CustomUser.objects.filter(username=request.user).update(git=username)
    #     commit.author['username'].update(
    #         commit = count
    #     )
    #     commit.filter(gitName=username).update(commit = count)
    #     commit.save()
    # else:

commapp/templates/about.html
<head>
    {% load static %} 
    <link rel="stylesheet" href={% static './css/about.css' %}>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <script src={% static './js/crawler.js' %}></script>
    <script src={% static './js/infinity.js' %}></script>
</head>
  
  <body>
    {% include 'nav.html' %}
    <div class="outsection">
        <div class="section1">
            <img class="hack1" src={% static './img/hack.png' %}/>

            <div class="mainment">
                <span>내 아이디어를</span>
                <span>내 손으로 실현한다</span>
            </div>

            <img class="hack2" src={% static './img/hack.png' %}/>
            <img class="line" src={% static './img/line.png' %}/>

            <div class="about">ABOUT US</div>
            <div class="mentbox1">
                <span>멋쟁이사자처럼 대학생은 멋쟁이사자처럼의 시작점으로</span>
                <span>2013년 서울대학교 30명의 학생에게 Ruby on Rails</span>
                <span>기반의 교육 프로그램을 진행하는 것으로 시작되었습니다.</span>
            </div>
            <div class="mentbox2">
                <span>그 후 총 9년간 "내 아이디어를 내 손으로 실현한다"라는</span>
                <span>가치 아래 전국 대학을 포함한 세계 130여개 대학에서 </span>
                <span>선발된 8,400여명의 학생들이 활동하였으며 교육</span>
                <span>프로그램을 통해 1,000여개의 서비스가 제작되었습니다.</span>
            </div>
            <div class="mentbox3">
                <span>현재 국내에서 가장 많은 학생들이 활동하고 있는</span>
                <span>프로그래밍 교육 프로그램이며, 현재는 Python</span>
                <span>& Django 기반으로 교육을 진행하고 있습니다.</span>
            </div>
            <img class="group" src={% static './img/group.jpeg' %}/>
        </div>

        <div class="midsection">
        <img class="RowLine1" src={% static './img/RowLine.png' %}/>
        <div class="university">LIKELION UNIV.</div>
        <img class="RowLine2" src={% static './img/RowLine.png' %}/>
        </div>

        <div class="infinitebox">
            <div class="marquee" id="mycrawler1">
                강원대학교 · 경북대학교 · 경상국립대학교 · 계명대학교 · 고려대학교(서울) · 고려대학교(세종) · 광운대학교 · 
            </div>
            <div class="marquee" id="mycrawler2">
                국민대학교 · 금오공과대학교 · 덕성여자대학교 · 동국대학교 · 동덕여자대학교 · 명지대학교(자연) · 삼육대학교 · 
            </div>
            <div class="marquee" id="mycrawler3">
                상명대학교 · 서강대학교 · 서울대학교 · 서울여자대학교 · 성공회대학교 · 성균관대학교 · 성신여자대학교 · 
            </div>
            <div class="marquee" id="mycrawler4">
                숙명여자대학교 · 순천대학교 · 숭실대학교 · 연세대학교(서울) · 영남대학교 · 을지대학교(성남) · 이화여자대학교 · 
            </div>
            <div class="marquee" id="mycrawler5">
                인천대학교 · 인하대학교 · 전남대학교 · 중앙대학교 · 충북대학교 · 한국외국어대학교(글로벌) · 한국외국어대학교(서울) · 
            </div>
            <div class="marquee" id="mycrawler6">
                한국항공대학교 · 한밭대학교 · 한서대학교(서산) · 한성대학교 · 한양대학교(서울) · 한양대학교(ERICA) · 홍익대학교 · 
            </div>
        </div>

        {% include 'footer.html' %}
  </body>
  </html>
  

commapp/templates/board.html
<head>
  {% load static %}
  <link rel="stylesheet" href={% static './css/board.css' %}>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
</head>
<body>
  {% include 'nav.html' %}
  <div class="outsection">
    <div class="topsection">
      <div class="section1">
          <div class="maintitle">커뮤니티</div>
          <button class="searchicon">
              <img class="icon" src={% static './img/searchicon.png' %}/>
          </button>
      </div>
      <div class="category">
        <p id="T" onclick="option(event)">TALK</p>
        <p id="I" onclick="option(event)">ISSUE</p>
        <p id="P" onclick="option(event)">PROJECT</p>
        <p id="C" onclick="option(event)">CONNECT</p>
      </div>
    </div>
    
    <div class="modal">
      <div class="modal_box">
        <div class="modal_content">
          <div class="searchtitle">검색</div>
          <div class="inputout">
            <form action="{% url 'search' %}" method="post">
              {% csrf_token %}
              <input id="search" name="search" value="{{q}}" placeholder="검색어를 입력하세요."/>
              <input id="submitbtn" type="submit" value=""/>
            </form>
          </div>
        </div>
      </div>  
    </div>
    <script src={% static './js/modal.js' %}></script>

    <div class="postsection">
      <div id="talk" style="display: block">
        {% for c in comm %} {% if c.tag == "talk" %}
        <a href="{% url 'board_detail' pk=c.pk %}">
          <div class="LinkComponent1">
            <div class="link">
              {% if c.img %}
                  <img src="{{c.img.url }}" class="representativeImg">
              {% endif %} 
              <div class="representativeTitle1">
                <div class="commit">{{ c.title }}</div>
                <div class="commit_detail">{{ c.text }}</div>
              </div>
            </div>
          </div>
        </a> 
        {% endif %} {% endfor %}
      </div>

    {% csrf_token %}
      <div id="issue" style="display: none">
        {% for c in comm %} {% if c.tag == "issue" %}
        <a href="{% url 'board_detail' pk=c.pk %}">
          <div class="LinkComponent1">
            <div class="link">
              {% if c.img %}
                <img src="{{c.img.url }}" class="representativeImg">
              {% endif %} 
              <div class="representativeTitle1">
                <div class="commit">{{ c.title }}</div>
                <div class="commit_detail">{{ c.text }}</div>
              </div>
            </div>
          </div>
        </a>
        {% endif %} {% endfor %}
      </div>
      
      <div id="project" style="display: none">
        {% for c in comm %} {% if c.tag == "project" %}
        <a href="{% url 'board_detail' pk=c.pk %}">
          <div class="LinkComponent1">
            <div class="link">
              {% if c.img %}
                <img src="{{c.img.url }}" class="representativeImg">
              {% endif %} 
              <div class="representativeTitle1">
                <div class="commit">{{ c.title }}</div>
                <div class="commit_detail">{{ c.text }}</div>
              </div>
            </div>
          </div>
        </a>
        {% endif %} {% endfor %}
      </div>
      
      <div id="connect" style="display: none">
        {% for c in comm %} {% if c.tag == "connect" %}
        <a href="{% url 'board_detail' pk=c.pk %}">
          <div class="LinkComponent1">
            <div class="link">
              {% if c.img %}
                <img src="{{c.img.url }}" class="representativeImg">
              {% endif %} 
              <div class="representativeTitle1">
                <div class="commit">{{ c.title }}</div>
                <div class="commit_detail">{{ c.text }}</div>
              </div>
            </div>
          </div>
        </a>
        {% endif %} {% endfor %}
      </div>
    </div>
</div>
{% if user.is_authenticated %}
<div class="btn_contain">
  <div class="newbtn">
    <a href="{% url 'board_post' %}">+ 글쓰기</a>
  </div>
</div>   
{% else %}
<div class="btn_contain">
  <div class="newbtn">
    <a href="{% url 'login' %}">+ 글쓰기</a>
  </div>
</div>
{% endif %}
<script src={% static './js/category.js' %}></script>

</body>

commapp/templates/board_detail.html
<html>
{% load static %} 
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href={% static './css/b_detail.css' %}>
    </head>
    <body>
        {% include 'nav.html' %}
        <div class="head-wrapper">
            <h1>{{ comm.title }}</h1>
            <div class="userbox">
                <a href="{% url 'board_update' pk=comm.pk %}">수정하기</a>
                <a href="{% url 'board_delete' pk=comm.pk %}">삭제하기</a>
            </div>
            <div class="inform">
                <div class="writer">{{ comm.user.nickname }}</div>
                <div class="date">{{ comm.date }}</div> 
            </div>
        </div>
        <div class="postsection">
            {% if comm.file %}
            <a href="{{comm.file.url }}" download>
                <div class="downbox">
                    <span class="chumboo">첨부파일</span>
                    <!-- <span class="filename">vkdlf.jpeg</span> -->
                    <span class="filename">{{ comm.get_file_name }}</span>
                    <img class="downicon" src={% static './img/download.png' %} />
                </div>
            </a>
            {% endif %} 
            {{ comm.text }}
            {% if comm.img %}
                <img class="postimg" src="{{comm.img.url }}">
            {% endif %}
        </div>

        <div class="seperate">
            <div class="line"></div>
        </div>

        <div class="commentsection">
            <h4>댓글</h4>
            {% if user.is_authenticated %}
            <form method="POST" action="{% url 'comment_create' pk=comm.pk %}">
                {% csrf_token %}
                <div>
                    {{ comment_form }}
                    <button type="submit">댓글 작성</button>
                </div>
            </form>
            {% else %}
            <a href="{% url 'login' %}">
                <div class="nocomment">로그인이 필요한 기능입니다</div>
            </a>
            {% endif %}
            
            {% if comm.comment_set.exists %}
                {% for comment in comm.comment_set.iterator %}
                <div id="{{comment.pk}}">
                    <!-- {{ comment.author.username }} -->
                    <div class="commentbox">
                        <div class="userinfo">
                            <div class="namedate">
                                <div class="comusername">
                                    {{ comment.user.nickname }}
                                </div>
                                <div class="comdate">
                                {% if comment.created_at != comment.modified_at %}
                                    (수정됨){{ comment.modified_at }}
                                {% else %}
                                    {{ comment.created_at }} 
                                {% endif %}
                                </div>
                            </div>
                            <div class="rede">
                                <a href="{% url 'comment_update' pk=comment.pk %}">수정</a>
                                <a href="{% url 'comment_delete' pk=comment.pk %}">삭제</a>
                            </div>
                        </div>
                        {{ comment.content }}
                    </div>
                    <!-- comment_update 함수에 댓글 pk전달 -->
                    <div class="recomsection">
                        <div class="recomexistbox">
                            {% for recom in comment.recomment_set.all %}
                                <div class="reoutbox">
                                    <div class="recomuser">
                                        <span class="recomname">🐾{{ recom.user.nickname }}</span>
                                        <a href="{% url 'recomment_delete' rc_pk=recom.pk %}" class="deletebtn">삭제</a>
                                    </div>
                                    <span class="recomcontent">{{recom.content}}</span> {{ created_at }}
                                </div>
                            {% endfor %}
                            <button class="rebtn" onclick="recomment()">
                                <img src={% static './img/down.png' %} /> 
                                <span class="btntext1">
                                    답글 달기
                                </span>
                            </button>
                            <div class="resection">
                                <button class="rebtn" onclick="recomment()">
                                    <img src={% static './img/up.png' %} />
                                    <span class="btntext1">
                                        숨기기
                                    </span>
                                </button>
                                <div class="rebox">
                                    <form method="post" action="{% url 'recomment_create' c_pk=comment.pk %}">
                                        {%csrf_token%}
                                        {{ recomment_form }}
                                    <input type="hidden" name="comment" value={{recomment.id}}>
                                    <input type="submit" value="댓글 등록" class="submitbtn">
                                    </form>
                                </div>
                            </div>
                        </div>
                        <button class="rebtn" onclick="recomment()">
                            <img src={% static './img/down.png' %} /> 
                            <span class="btntext1">
                                답글 달기
                            </span>
                        </button>
                        <div class="resection">
                            <button class="rebtn" onclick="recomment()">
                                <img src={% static './img/up.png' %} />
                                <span class="btntext1">
                                    숨기기
                                </span>
                            </button>
                            <div class="rebox">
                                <form method="post" action="{% url 'recomment_create' c_pk=comment.pk %}">
                                    {%csrf_token%}
                                    {{ recomment_form }}
                                <input type="hidden" name="comment" value={{recomment.id}}>
                                <input type="submit" value="댓글 등록" class="submitbtn">
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            </div>
        </div>
        <script src="/static/js/recomment.js"></script>
</body>
</html>

commapp/templates/board_post.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href={% static './css/b_post.css' %}>
  </head>
  <body>

      {% include 'nav.html' %}
      <div class="outsection">
        <div class="maintitle"></div>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %} 
          {{ form.as_p }}
          <div class="btnbox">
            <button type="submit">등록하기</button>
          </div>
        </form>
        
      </div>
      {% include 'footer.html' %}
    <script src={% static './js/enter.js' %}></script>
  </body>
</html>

commapp/templates/commit.html
<head>
    {% load static %} 
    <link rel="stylesheet" href={% static './css/commit.css' %}>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
</head>
  
  <body>
    {% include 'nav.html' %}
    <div class="outsection">
        <div class="box">
            <span class="ment1">이번주 작업한 레포는</span>
            {% for i in name %}
            <span class="count1">{{ i }}</span>
            {% endfor %}
            <span class="ment2">총 커밋수는 <span class="count2">{{ repos }}</span>입니다</span>
        </div>
        <a href="{% url 'commit_rank' %}">
            <div class="gobtn">
                다른 사자들의 랭킹 보러가기
            </div>
        </a>
    </div>
    
    {% include 'footer.html' %}
</body>
</html>